---
title: Blogpost1
author: Team
date: '2022-10-14'
slug: []
categories: []
tags: []
description:
toc: yes
authors: []
series: []
lastmod: '2022-10-12T09:41:03-04:00'
featuredVideo: ~
featuredImage: ~
---

<<<<<<< HEAD
#Data Set 1 Description/link


#Data Set 2 Description/link


#Data Set 3 Description/link






=======
 ~“The State of the World’s Children”: Nutrition Tables (2019) *since I cannot find a direct link, please use this link: https://data.unicef.org/resources/dataset/sowc-2019-statistical-tables/
and scroll down to “Tables 7 and 8- Nutrition” to view the tables.*

This data comes from UNICEF, the United Nations International Children’s Fund, which is a non-profit organization dedicated to helping children across the world who suffer from poverty, violence, and lack of education. Their website includes a strong database that reveal how the state of children in every region of the world. They believe that equity, the core of their mission, is not possible without gathering this data. According to their website, they are the leaders in data collection in this topic of interest.  

This particular data set is the Nutrition report for preschool/school age children and women that ranges from 2013-2016. Its sources include national household surveys, and modeled estimates from UNICEF. One table has approximately 200 rows and 18 columns, but we believe that we could find a way to combine the two to increase that number. There is much opportunity to clean the data, as there are some missing values, values that belong to different years, and a few other notes listed for us at the bottom of the table. The main question we would like to ask would be what the most acceptable condition is for children to have a “healthy nutrition”, and possibly being able to define more clearly about what that means for children across the world. 

#just a rough draft of some of the questions we need to answer for the post - can edit whatever you want! - anamaria#

The second data that we are interested in observes the ongoing Ukraine conflict through Twitter. One of the questions here could be how the social media platform, Twitter, contributes to the public opinion/reporting about the ongoing war in Ukraine. It could potentially "measure" how powerful Twitter (or lack thereof) can be during serious international conflicts. 
This data is from --- and has approx. -- rows and -- columns. We would start by loading and cleaning the data by _. Some potential challenges with this data could be --. 

Our final data set is from the CDC, which gives information about E-cigarette legislation and its affect on youth. We could explore how state level preemption on laws surrounding youth access to e-cigarette affect the e-cigarette usage among the youth population. (add about how the CDC collected this data here?)

(About the data - #rows/columns, how we would clean the data, possible challenges, the overall mission)
>>>>>>> cc4856fcef401953cc829827bad41a67f3ca7797
