---
title: 'EDA Continued and Tentative Thesis' 
author: Team
date: '2022-11-30'
slug: []
categories: []
tags: []
description: ~
toc: yes
authors: []
series: []
lastmod: '2022-11-30T09:53:27-05:00'
featuredVideo: ~
featuredImage: ~
---

This week we focused on continuing our EDA by coming up with a variety of different ideas incorporating all of our data and variables. 
Our first step was to average the years in our income/mortality rate data set to match the year average of our nutrition data set so we could create plots that represent the data in the same time period, which is 2013 - 2018. Using the nutrition data set we will begin by creating a few uni variate graphs to present the variables. These variables will include low birth weight ("LowBirthWT%"), minimum meal frequency (""MinMealFreq%"), and zero vegetable consumption ("ZeroVegtable%"), and minimum diet diversity ("DietDiversity%"). 

We first decided to give a visual for the low birth weight by each region. To do this, we took our Country variable and were able to organize them into their region, so we would be able to represent it more clearly, rather than have over 200 countries (colors). In one of our bar charts, the end results showed us that  South Asia had a significantly larger total percent of lowbirthweight in children than any other region. 


Next, we will transition into a bivariate analysis using our additional data sets. 
Our combined income/mortality rate data sets will we plan to explore a few relationships such as: 
The decrease over time in mortality rates versus the level of income (shown on our analysis page using color to represent this level). 


We plan to also implement the population data set as an additional factor, as we believe that this could also potentially impact the mortality rates, as well as the access to our nutrition variables. This will also help create a more comprehensive profile of each country.  

Based on our initial findings, we will create a linear regression to predict mortality rates based on nutrition variables, income, and population. 

Now we have also successfully created our combined data set that houses all of our nutrition variables, income per capita, and mortality rates. 



## Building our Tentative Thesis

Our first thoughts on our tentative thesis is that as we create our linear model, we will be able to explore the relationships between our current working variables. Our thesis could possibly end up being that in the countries with lowest mortality rates, these X factors are either increasing/decreasing/or impacting the rate. This way we can build a comprehensive profile of the characteristics of significant countries (whose mortality rates are either the lowest or highest). 

## Next Steps: 

We still have a few unresolved issues that have inhibited the growth of our analysis. But we plan to do the things below to resolve these issues and continue our depth in analysis:

1. Code the linear models
2. Create a function that includes "k"s and "M"s for the population size data set (in load_and_clean data)
3. Create a variable in the income_mortality data set that assigns the world region (e.g. Africa, Europe, North America etc.) to each country
4. Get ideas for our interactive and further expand it
5. Find more datasets to include more variables in the analysis







